version: "3.3"
services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - ./volumes/mongodb:/data/db
    restart: unless-stopped
